#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidAppExample.Resource", IsApplication=true)]

namespace AndroidAppExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int alphaSlider = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int alphaSliderView = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int density = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int initialColor = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int lightnessSlider = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int lightnessSliderView = 2130771973;
			
			// aapt resource value: 0x7f01000a
			public const int pickerButtonCancel = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int pickerButtonOk = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int pickerColorEditTextColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int pickerTitle = 2130771976;
			
			// aapt resource value: 0x7f010004
			public const int wheelType = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030000
			public const int default_padding_side = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int default_preview_height = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int default_preview_image_height = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int default_slider_bar_height = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int default_slider_handler_radius = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int default_slider_height = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int default_slider_margin = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int default_slider_margin_btw_title = 2130903047;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int CIRCLE = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int FLOWER = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int color_indicator = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int color_picker_view = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int image_preview = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int v_alpha_slider = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int v_lightness_slider = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int color_preview = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int color_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int color_widget = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Main = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int picker_edit = 2130837508;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int PickerEditText = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorPickerPreference = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int ColorPickerPreference_alphaSlider = 0;
			
			// aapt resource value: 6
			public const int ColorPickerPreference_alphaSliderView = 6;
			
			// aapt resource value: 2
			public const int ColorPickerPreference_density = 2;
			
			// aapt resource value: 3
			public const int ColorPickerPreference_initialColor = 3;
			
			// aapt resource value: 1
			public const int ColorPickerPreference_lightnessSlider = 1;
			
			// aapt resource value: 5
			public const int ColorPickerPreference_lightnessSliderView = 5;
			
			// aapt resource value: 10
			public const int ColorPickerPreference_pickerButtonCancel = 10;
			
			// aapt resource value: 9
			public const int ColorPickerPreference_pickerButtonOk = 9;
			
			// aapt resource value: 7
			public const int ColorPickerPreference_pickerColorEditTextColor = 7;
			
			// aapt resource value: 8
			public const int ColorPickerPreference_pickerTitle = 8;
			
			// aapt resource value: 4
			public const int ColorPickerPreference_wheelType = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
